### PR TITLE
Add label support to REVIEWERS and NOTIFIED files.

### PR DESCRIPTION
**Pull request by csilvers**
## Summary:
This lets you specify rules like this:
```
something_changed: **/* @notifyme
```

And when we add the NOTIFIED section to the github PR, it will now say:
```
@notifyme (something_changed): file1 file2 file3
```
(For rules without labels, the output is unchanged.)

This is helpful for knowing _why_ you were being notified for a
particular PR, since as we add more NOTIFIED rules it can get harder
to tell.

I added the support for REVIEWERS as well, since it was easy, though
I'm not sure how useful it is there.

While in the area, I couldn't help but clean up the existing code a
bit, especially simplifying some of the regexp-parsing logic (at the
cost of more parentheses in the regexp).

Issue: https://khanacademy.atlassian.net/browse/FEI-5970

## Test plan:
yarn flow
yarn jest

### CODE REVIEW

**Review by lillialexis — APPROVED** [review]
Thanks so much, and thanks for the clean-up!

My only feedback is to please add more examples, because the `allfiles` example, in isolation, if I didn't know what I was looking at, my brain would think that it had to do with all the files specifically, as opposed to an example of how a label would work. If that makes sense. 😄

**Comment by lillialexis** [comment]
Also, does this only work with the file-matching part of Gerald or the regex matching too? If the latter, a regex of a regex, are there any cases where we would get false positives because of a colon? I think not, because probably it's looking for the regex to be surrounded by `/`s... 🤔

**Comment by csilvers** [comment]
I've renamed `allfiles` to `something_changed`.  Does that make things clearer?

**Comment by csilvers** [comment]
(In the PR description.  In the PR itself I have:
```
# This rule will notify @owner1 on changes to all files, and the rule
# has a label "allfiles", which will be included in the github PR info.
# allfiles: **/*                @owner1
```
which seems pretty clear?  But let me know if not.

**Comment by csilvers** [comment]
> Also, does this only work with the file-matching part of Gerald or the regex matching too? If the latter, a regex of a regex, are there any cases where we would get false positives because of a colon? I think not, because probably it's looking for the regex to be surrounded by `/`s... 🤔

I mention this in the commit message.  Regexps have to start with a `"`, so there's no chance of confusion.

(And definitely it works with both!)

**Pull request merged**
